import "styles/globals.scss";
import "styles/reset.scss";
import type { AppProps } from "next/app";
import Head from "next/head";
import { Barlow_Semi_Condensed } from "next/font/google";

const font = Barlow_Semi_Condensed({
	weight: ["400", "600", "700"],
	style: ["normal"],
	subsets: ["latin"],
});

export default function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={font.className}>
				<Component {...pageProps} />;
			</main>
		</>
	);
}
